### ISSUE TITLE
Default Hub registry gone when alternative registries integrated

### ISSUE THREAD

**Issue by Slave2WAF** [fmartinou/whats-up-docker#107]
This is a great project!

Problem:  When running a new instance of 5.15.0 with alternative registries integrated (e.g., LSCR), containers based on Docker Hub images don't show up in the UI.  After the Hub registry is manually added to the docker-compose file, all containers are visible.

Expected behavior:  Since WUD documentation states that "By default, WUD is working out-of-the-box with public images hosted on [Docker Hub](https://hub.docker.com/).", I'd expect WUD to maintain anonymous Hub access even after integrating alternative registries.

**Comment by fmartinou** [comment]
Hi,

Thank you for your support!

I can understand that is confusing.
(the proof being that you're not the 1st user to fall into the trap ;)

Your request makes sense.
The trick is how to implement without adding more confusion because the purpose is to keep things simple.
(this "by default Docker Hub configuration" is intended to get a working solution for most users so they don't need to tweak the configuration).

My idea:

**WUD will configure at startup all registries that can be queried anonymously
*unless this registry is explicitly configured by the user* (Docker hub credentials, GHCR credentials...).**

(this behavior will apply to the following registries: HUB, LSCR, GHCR, QUAY)

What do you think?

**Comment by Slave2WAF** [comment]
This makes good sense to me as long as two conditions are met:

1. Explicit configuration of a registry does not disable default configuration of other registries
2. The new registry configuration model is reflected in the documentation. :-)

**Comment by ranrinc** [comment]
Love this project and being used it for my home-labs. I 2nd to this features since I used WUD for all my docker and since I'm running Proxmox most of my apps running on individual LXC, so I have many docker container and monitor it via portainer and WUD is great. However since I also running HA which mostly host on GHCR, then it create problem on several of supervised HA.

**Comment by fmartinou** [comment]
Hi,

It's implemented in `5.16.0`.
The documentation has been updated.
Wow the following registries are configured by default
- GHCR
- HUB
- LSCR
- QUAY

Thank you for your feedback!

**Comment by Slave2WAF** [comment]
Thank you so much for making the enhancement so quickly!  I deleted a few of my WUD registry configurations and the new defaults worked perfectly.

I think this change significantly enhances the experience for new users and streamlines the onboarding process.   Super job!

**Comment by fmartinou** [comment]
Thanks for the encouragement! 👍
