### ISSUE TITLE
Icon Labels for Simple Icons and FAB Must Use a Colon

### ISSUE THREAD

**Issue by kschlichter** [fmartinou/whats-up-docker#130]
I've recently set up WUD and I love the work you're doing.  It's the perfect solution to a specific issue and it does what it does well.  

This is very minor, but could save someone else a few hours in the future.  [Documentation](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=labels) for the label `wud.display.icon` says "Valid Material Design Icon prefixed by mdi: or mdi-" but the dash _only_ works for Material Design Icons. 

I've found that if I define the label with a [Simple Icons](https://simpleicons.org/) icon and a dash `wud.display.icon=si-grafana` no entity appears in Home Assistant.  Changing it to `wud.display.icon=si:grafana` does populate the entity, however, and the proper icon is used.  The same is true for [Font Awesome](https://fontawesome.com/) icons.  Using `wud.display.icon=fab-expeditedssl` for certbot will never get an entity while `wud.display.icon=fab:expeditedssl` works.   SI and FAB seem to require the si: and fab: format and only MDI can use the mdi- format.  I suppose the easiest fix would be to change the documentation to something like:

> Valid Material Design Icon, Font Awesome Icon, or Simple Icon prefixed by mdi: or fab: or si:

**Comment by fmartinou** [comment]
Hi,

Thank you for your support and your feedback 👍 

Actually icons are displayed both in HA and in WUD UI.

- HA can display icons from Material Design Icons, Simple icons and Font awesome whereas WUD can only display icons from Material Design Icons
- HA expects the icon to be prefixed by `mdi:` whereas WUD expects the icon to be prefixed by `mdi-`.

That's why I had to do some trivial transformations to get icons working in both contexts.

I'm going to see if I can add support for FAB and SI icons in WUD UI

**Comment by fmartinou** [comment]
The version `5.17.0` has just been released.

You can now use Material Design icons, Fontawesome icons or Simple icons (using `:` or `-` syntax) ([The doc has been updated](https://github.com/fmartinou/whats-up-docker/tree/master/docs/configuration/watchers#customize-the-name-and-the-icon-to-display))
