### ISSUE TITLE
Use Docker Secrets in Env Vars

### ISSUE THREAD

**Issue by mbelangergit** [fmartinou/whats-up-docker#162]
I would like to use the Docker Secrets in the configuration environment variables for WUD like I do for my other containers.

I'm looking for something similar to what linuxserver.io is doing on their images. Something like prepending `FILE__` or appending `_FILE` (like Nextcloud and Authelia are doing) to the environment variables names.

Thanks!

**Comment by fmartinou** [comment]
Hi,

It's implemented (https://github.com/fmartinou/whats-up-docker/commit/2d83d7cde5ce531400b9951bd843eaef9c8923b0) and it will be part of the next release.

The feature will allow to load configuration values (including secrets at the first place) from external files by appending the `__FILE` suffix to the original env var name.

For example, instead of providing the Basic auth details as
```
WUD_AUTH_BASIC_JOHN_HASH=$$apr1$$aefKbZEa$$ZSA5Y3zv9vDQOxr283NGx/
```

You'll create an external file with the appropriate permissions (let's say `/tmp/john_hash`) containing the secret value (`$$apr1$$aefKbZEa$$ZSA5Y3zv9vDQOxr283NGx/`).

Then you'll reference this file with the following env var
```
WUD_AUTH_BASIC_JOHN_HASH__FILE=/tmp/john_hash
```
