### ISSUE TITLE
Experiencing rate limits

### ISSUE THREAD

**Issue by t-pohl** [fmartinou/whats-up-docker#179]
Hey everybody,

has anybody experienced rate limits from Docker Hub while using WUD? According to the [documentation of Docker Hub](https://docs.docker.com/docker-hub/download-rate-limit/) "pull rates limits are based on individual IP address. For anonymous users, the rate limit is set to 100 pulls per 6 hours per IP address. For [authenticated](https://docs.docker.com/docker-hub/download-rate-limit/#how-do-i-authenticate-pull-requests) users, it is 200 pulls per 6 hour period." This should definitely be sufficient for me and always was in the past but since I run WUD (without auto updates, ~20 containers which are watched) I frequently experience rate limits:
`Error response from daemon: toomanyrequests: You have reached your pull rate limit.` 

Does WUD use pulls to perform its checks such that the limit is hit and if yes can you throttle it?

**Comment by fmartinou** [comment]
Hi @t-pohl ,

> Does WUD use pulls to perform its checks such that the limit is hit and if yes can you throttle it?

WUD doesn't perform pull actions but it performs API calls which are counted from the quota.

To get around the Docker hub rate limits, you can use/combine the following 4 techniques:

1. Slow down the watch frequency (`WUD_WATCHER_{watcher_name}_CRON`) ; [please find the documentation here](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=variables)

2. Create a free Docker Hub account to increase the quotas ; [please find the documentation here](https://fmartinou.github.io/whats-up-docker/#/configuration/registries/hub/?id=configure-authentication-using-logintoken)

3. Use immutable `semver` tags instead of mutable tags for your containers because the `watch process` involves lots more API calls when `image digests` must be analyzed [as mentioned in the doc here](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/)
![image](https://user-images.githubusercontent.com/16061231/201476985-5ebfded4-91a0-4dbd-bcd2-7b0846d351c9.png)

5. Use images from alternate registries when possible (the [Github Container Registry](https://fmartinou.github.io/whats-up-docker/#/configuration/registries/ghcr/) for instance)

**Comment by t-pohl** [comment]
Thank you so much!
