### ISSUE TITLE
Blank images

### ISSUE THREAD

**Issue by siredwin** [fmartinou/whats-up-docker#18]
Version 3.0.0 and 3.0.1 show blank images.
2.3.1 still works.
![What-s-up-Docker-](https://user-images.githubusercontent.com/8451465/97743713-b1398a00-1aab-11eb-9773-bd0e53ca0a09.png)
![What-s-up-Docker-2](https://user-images.githubusercontent.com/8451465/97743724-b565a780-1aab-11eb-88a3-943f2bee8ba3.png)

**Comment by fmartinou** [comment]
Hi,

Please notice that v3 is not backward compatible with v2.

Did you pay attention to the following points ([as mentioned in the changelog](https://fmartinou.github.io/whats-up-docker/#/CHANGELOG?id=_300))?
1. Delete the /store/wud.json (if you have mounted /store on a host directory)
2. Review all the configuration variables used because some of them has been renamed

If so, please run wud with `WUD_LOG_LEVEL=debug` and paste the log here along with your wud configuration.

Thanks!

**Comment by siredwin** [comment]
My bad! I did not notice that the variables changed in version 3. It is all good now.
