### ISSUE TITLE
Problem with latest tag on various

### ISSUE THREAD

**Issue by jasongordon** [fmartinou/whats-up-docker#22]
Most of my docker images from dockerhub are being used with the latest tag but WUD is reporting all kinds of crazy versions.
![Screen Shot 2021-01-09 at 2 02 26 PM](https://user-images.githubusercontent.com/2027525/104106392-7611bf00-5283-11eb-8ec5-8eea64258816.png)
Bazarr i am already at .9.0.7
Radarr i am at 3.0.1.4259 and it is showing some weird tag of version-v0.2.0.1504

My docker-compose file specifies latest for all of these apps.  Is this a bug?

Thanks

**Comment by fmartinou** [comment]
Hi,

Looks definitely like a bug :/

I guess that the implementation, when the current version is not semver, lexically sorts the versions a -> z then returns the highest...
which is just wrong.

Thanks for raising the issue; I will fix it!

Actually WUD is not very useful for non semver versions...
Its primary goal is to detect when a new semver version is available, not when a tag (eg 'latest') has been overwritten.

I would strongly encourage you to start using semver tags instead of 'latest' tags ;)

Regards

**Comment by jasongordon** [comment]
I can switch to using semver in my docker-compose files.  Will WUD work if I specify a major version only, ie:  linuxserver/nzbhydra2:3

How would I use it for radarr where latest seems to point to this tag:  version-3.0.1.4259
Would I use linuxserver/radarr:version-3

Just not sure it will work based on the way these projects tag releases.  Thoughts?
https://github.com/linuxserver/docker-nzbhydra2/releases

**Comment by fmartinou** [comment]
I'd recommend you to use the most accurate tags possible (MAJOR.MINOR.PATCH).

Because tag naming is inconsistent on Docker hub (euphemism ;), you need to help WUD finding the right one by filtering false matches.

To do that, you need to provide a Regex matching the tag format you're interested in.

Below a working Docker Compose example for radarr and hydra.
(for hydra, it's up to you to use versions like `version-v3.8.0` or `v3.8.0-ls5`.)

```yaml
version: '3'

services:

    hydra1:
        image: linuxserver/nzbhydra2:version-v3.8.0
        labels:
            - 'wud.tag.include=^version-v[0-9]\d*.[0-9]\d*.[0-9]\d*$$'

    hydra2:
        image: linuxserver/nzbhydra2:v3.8.0-ls5
        labels:
            - 'wud.tag.include=^v[0-9]\d*.[0-9]\d*.[0-9]\d*-ls[0-9]\d*$$'

    radarr:
        image: linuxserver/radarr:version-3.0.0.4235
        labels:
            - 'wud.tag.include=^version-[0-9]\d*.[0-9]\d*.[0-9]\d*.[0-9]\d*$$'
```

And what WUD has detected:
![image](https://user-images.githubusercontent.com/16061231/104166308-e1ca6800-53fa-11eb-9cd0-b25cb71f4460.png)

**Comment by jasongordon** [comment]
First, i want to say I appreciate the attention you are giving this issue.  
In my docker-compose file, I have been using the "latest" tag so that when there is a new version available, I just need to do the following to update my images:
docker-compose down
docker-compose pull
docker-compose up -d

If I instead, specify a specific version tag in my docker-compose.yml file, say as you suggested:
hydra2:
        image: linuxserver/nzbhydra2:v3.8.0-ls5

Then once WUD docker notifies of a new version would the update procedure just be to do a "docker-compose down" and then just change the above in the docker-compose.yml to:
hydra2:
        image: linuxserver/nzbhydra2:v3.9.0-ls6
Then just restart: "docker-compose up -d" ?

Also what do those ls5, ls6 suffixes mean?

**Comment by fmartinou** [comment]
Even easier...
You don't need to run `docker-compose down` and `docker-compose pull` anymore :)

Just:
1. Change in your docker-compose.yml file the version from `v3.8.0-ls5` to `v3.9.0-ls6`
2. Run `docker-compose up -d`

And let Docker Compose automatically:
- pull the `v3.9.0-ls6` tag
- remove the current hydra container in `v3.8.0-ls5`
- run a new container with the `v3.9.0-ls6` version

Even better, thanks to that, your other services won't be restarted!

About ls5, ls6 suffixes... they are specific to LinuxServer based images.
The LinuxServer team weekly updates their base images and triggers builds on all child images.
So if only the `ls` part changes, it means that the service (lyra, radarr...) has not been updated but the underlying base image was.

Regards

**Comment by jasongordon** [comment]
Thanks for your help on this.  So are you going to try to add support for projects that use the `latest` tag?  Take `organizr/organizr` which just uses the `latest` tag along with architecture tags.  Is there a way to support this?

**Comment by fmartinou** [comment]
Hi,

Supporting `latest` tags, or more generally speaking "tag overwriting", implies to know when occured the last push on the Registry.
Unfortunately, this information is not exposed through the official [Docker Hub API V2](https://docs.docker.com/registry/spec/api/#listing-image-tags) (which is the standard even for other registries like ECR, GCP...).

Furthermore, dealing with mutable tags is not the spirit of WUD; I strongly believe that it's a bad habit ;)
([see here a blog article clearly explaining why](https://vsupalov.com/docker-latest-tag/)).

But...

Docker Hub also exposes a non standard REST API which would allow to implement this ([see here](https://www.npmjs.com/package/docker-hub-api#tagsusername-repository-options)).
So it should be possible to add this feature but it'd work only with the Docker Hub Registry (and I won't be able to gurantee that it'll work in the future).

Because most users use the Docker Hub as a Registry, I will however add the feature: it's worth it.
Thanks for your suggestion ; I add it to my TODO list!

**Comment by fmartinou** [comment]
@jasongordon @rasmuslp,

Now WUD is also supporting non semver tags (e.g `latest`) 🎉 .
It's still in beta stage but you can already give it a try if you're interested (`fmartinou/whats-up-docker:develop` version).

To explain a little bit:
- WUD now compares the digest of the running image with the digest of the image manifest from the Registry
- If the digests are not equal, WUD reports that the image can be updated

Thanks for your feedback!

*N.B. The version is non backward compatible => Please remove /store/wud.json before upgrading*

**Comment by fmartinou** [comment]
It's now available in version `4.0.0`.

**Comment by rasmuslp** [comment]
I'm testing this with the `unifi-rpi` image referenced earlier (snippet from Ansible):
```yaml
image: 'ryansch/unifi-rpi:6.0.45'
labels:
          'wud.tag.include': 'latest'
```

Currently `latest` is the same as `6.1.71`, so I would expect to see that running image is not the same as described by the watch filter.

However, the UI shows the same sha for the Digest column and the New Digest column. Curiously, I cannot identify this sha as matching either `6.0.45` or `latest`: `sha256:7c3d09c3dc66f681b2f2ee3240337beea27f567f9e6ab9620db9480d2680feba`

It's not clear to me, if this use case is supported, i.e. specific image, tracking a meta-tag. In an ideal world, I would hope that WUD could identify that the digest of the `latest` tag is also tagged with `6.1.71`, and (also) show this in UI and email notifications. But I'm happy just knowing the digest changed :)

**Images**
* `6.0.45` https://hub.docker.com/layers/ryansch/unifi-rpi/6.0.45/images/sha256-129693c8e75d312cb7d3f0bdee52e79b57cf77cd05f469656f40ef0bfe451529?context=explore
* `6.1.71` https://hub.docker.com/layers/ryansch/unifi-rpi/6.1.71/images/sha256-10bb2824e0345bb89cb348cc295e20feb651eb3eeaf7b981b4368d2f89763d9d?context=explore
* `latest` https://hub.docker.com/layers/ryansch/unifi-rpi/latest/images/sha256-10bb2824e0345bb89cb348cc295e20feb651eb3eeaf7b981b4368d2f89763d9d?context=explore

**Comment by fmartinou** [comment]
Can you upgrade to `4.0.1`? (I fixed an issue regarding digests).

I'll soon enrich the documentation to explain how the update resolution algorithm works.

Concerning your example above, your configuration is not consistent because you run a semver version and you ask wud to filter on latest tag only.

A more appropriate configuration would be:
```
image: 'ryansch/unifi-rpi:6.0.45'
labels:
          'wud.tag.include': '^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*)$$'
```

With that configuration, 2 things can happen :
1. WUD founds a greater semver tag (eg.. `6.0.46`) so it reports that the image can be updated (you already know about it because it's the original feature of wud)
2.  WUD founds that the digest associated to the tag `6.0.45` changed so it reports that the image can be updated as well

This 2nd feature allows to cover usecases where the image editor publishes every version as `X.Y.Z` and `X.Y` and `X` tags at the same tag.
I understand it is what `docker-unifi-rpi` does.
So you could choose for example to track major versions or minor versions like this
```
image: 'ryansch/unifi-rpi:6'
labels:
          'wud.tag.include': '^([0-9]\d*)$$'
```
```
image: 'ryansch/unifi-rpi:6.0'
labels:
          'wud.tag.include': '^([0-9]\d*)\.([0-9]\d*)$$'
```

**Comment by rasmuslp** [comment]
I destroyed and recreated with version 4.0.1, but the behaviour is exactly the same.

My conflict with your suggestion is, that I would like to specify the exact version. I use versioned Ansible playbooks to manage containers. Having exact versions in theses gives me both history of what was running where and when, and it serves as a trigger to Ansible, so that the container gets recreated.

Note that `latest` / `6` is not the highest version number, of the stable releases. 6.2 series is the current release candidates.

I see that for my suggestion to work, the resolved watch-tag's digest should somehow also be taken into account.

As I understand it now, with the current functionality, I should be able to set 
```yaml
image: 'ryansch/unifi-rpi:6.0.45'
labels:
          'wud.tag.include': '^6\.1\.([0-9]\d*)$$'
```
in order to get valid update notifications for the latest stable releases of that particular image.

**Comment by fmartinou** [comment]
Is there any reason you want to only track a range of upper versions?

I think I'm working the same way as you:
Generally speaking, I try to avoid tags which can be overridden
I track on Git the exact versions I'm running (x.y.z if possible) and I'm watching for upper x.y.z versions only.

**Comment by rasmuslp** [comment]
> The double $ are there to prevent Docker Compose to interpolate the string.
> I had an issue with that at the beginning.
> Maybe it's not necessary anymore?

Bottom one is `unifi-rpi`, and the only one declared with `$$`, but all through Ansible.
<img width="1254" alt="Screenshot 2021-05-06 at 21 23 56" src="https://user-images.githubusercontent.com/1242952/117354418-952b0100-aeb1-11eb-8010-cfd67a4275fa.png">
Seems like everything is passed through 1:1.

**Comment by rasmuslp** [comment]
> Is there any reason you want to only track a range of upper versions?
> 
> I think I'm working the same way as you:
> Generally speaking, I try to avoid tags which can be overridden
> I track on Git the exact versions I'm running (x.y.z if possible) and I'm watching for upper x.y.z versions only.

If I set the open regex, as seen in the screenshot in the previous post, then it will also match `6.2.23`, which is a release candidate. I'm not too impressed with the amount of bugs in the latest stable versions, so the thought of release candidates are a bit frightening thb. Unfortunately, with the way the image is tagged, there is no way of distinguishing stable from rc on the version number. The only way to follow the latest stable release, with an unbound range, would be to track the `latest` tag.

**Comment by fmartinou** [comment]
Oh... I understand better now...

So the root cause is a bad design of tag management on unify-rpi projet 🤔.
Semver defines conventions to tag release candidates.
Maybe you should talk to the developers for changing that?
If they could just suffix the RC with something indicating it's not a release, it would be enough.
Something like x.y.z-rc would be fine.
