### ISSUE TITLE
[feature request] Homepage support

### ISSUE THREAD

**Issue by zvarg** [fmartinou/whats-up-docker#228]
It would be great, if wud supports [Homepage](https://github.com/benphelps/homepage).

**Comment by fmartinou** [comment]
Hi,

Thanks for the suggestion! 😃
(I wasn't aware of this tool).

I guess that the challenge is not to add `wud` to the page because it seems to be already possible using the "generic" service capabilities:
```
- Group A:
    - Service A:
        href: http://localhost/
        description: This is my service
        server: my-server
        container: my-container
```

But rather to have `wud` widgets (like the example below)?
![image](https://user-images.githubusercontent.com/16061231/219108526-523854f8-afd4-4d38-a52d-be806b5e516b.png)

?

**Comment by zvarg** [comment]
Thanks for the tip, I will check on it.

**Comment by fmartinou** [comment]
Hi,

There is now an official widget https://gethomepage.dev/en/services/whatsupdocker/ 🥳 

(see #270)
