### ISSUE TITLE
Make paths relative

### ISSUE THREAD

**Issue by mpietruschka** [fmartinou/whats-up-docker#231]
I tried to make wud run with traefic/reverseproxy under http://ip/wud . Before forwarding the request the path is changed into /. 

By trying to load all the resources from http://ip/resources... things fail. The landing page seems to show up as a blank page. The content of the website doesn't show up.

Tha API seems to respond well with the reverseproxy.

Could you please implement a way one could setup a different path than /? Like with relative paths...

https://cli.vuejs.org/config/#publicpath

**Comment by fmartinou** [comment]
Hi @mpietruschka ,

I am not mistaken, the Vue CLI `publicpath` option is used at build time (when you now the path where the app will be deployed)

> By default, Vue CLI assumes your app will be deployed at the root of a domain, e.g. https://www.my-app.com/. If your app is deployed at a sub-path, you will need to specify that sub-path using this option. For example, if your app is deployed at https://www.foobar.com/my-app/, set publicPath to '/my-app/'.

What you ask for, is the possibility to deploy `wud` at any path; I need to do some research to understand how to do that 🤔 .

**Comment by fmartinou** [comment]
> Googling for "vue js relative path" has shown up this posts. They claim that things work, when you set relative paths at buildtime "./" or process.env.BASE_URL.

That 'd work for the path you define **at build time**.
But I cannot predict the path you (or any other user) want to deploy `wud` to 😀 .
So these solutions won't work.

Side question; why do you need to rewrite the path?
Can't you just let Traefik route to `wud` using subdomain routing (e.g. https://wud.my-domain.com)?
(that's what most users do).

**Comment by mpietruschka** [comment]
> That 'd work for the path you define **at build time**. But I cannot predict the path you (or any other user) want to deploy `wud` to 😀 . So these solutions won't work.

Yes thats right.  "publicPath"s  value is set in the generated Code at build-time. But the set prefix string "./" or process.env.BASE_URL are resolved during runtime. That way it should be unneccessary setting an individual path. The default Value for publicPath is "/". It could even help setting it to an empty string.

Did you try the above example from my compose-file?

> Side question; why do you need to rewrite the path? Can't you just let Traefik route to `wud` using subdomain routing (e.g. https://wud.my-domain.com)? (that's what most users do).

Sure, but my users are not able to change their DNS-Server to make WUD reachable by a subdomains. Espacialy in a local setups.  Connecting the server to another networks and having to change the underlaying DNS would add a lot overhead, too.

**Comment by fmartinou** [comment]
I had to revert it because it breaks the app.
The reason is that this option is only viable for simple Vue apps and not for multi-page apps as mentioned in the Vue.js documentation:

![image](https://github.com/fmartinou/whats-up-docker/assets/16061231/956cd5ba-d8b3-4509-b65f-2b5f5910c8be)

So sorry for your use-case but I won't fix it.
I guess that a workaround should be possible using pure Reverse-Proxy configuration and path rewriting.

**Comment by mpietruschka** [comment]
> I had to revert it because it breaks the app. The reason is that this option is only viable for simple Vue apps and not for multi-page apps as mentioned in the Vue.js documentation:
> 
> ![image](https://user-images.githubusercontent.com/16061231/251689187-956cd5ba-d8b3-4509-b65f-2b5f5910c8be.png)
> 
> So sorry for your use-case but I won't fix it. I guess that a workaround should be possible using pure Reverse-Proxy configuration and path rewriting.

Thank's for trying.

You can try my example. But pure path rewriting din't work.

**Comment by alnviana** [comment]
I know this issue is old, but I'm going to add a few things here to avoid other people wasting their time trying. I've given up on using this project, but maybe it can help someone else.
---
To begin with, there is no stable way of solving this in a reverse proxy. This can direct a /wud/ path to /, but it's no use if the application processes it and returns to the browser that the paths are / and not /wud/.

The same problem occurs if everything is a relative path, because for the browser it is relative to <protocol>://<domain>:<port>, so any link or resource that is created in this way will end up assembling the URL without /wud/.

About using “path rewriting”, just giving more context to what the other user said.
It really isn't feasible to use it, because it works by searching for something and replacing it in ALL the content that is passed. In addition to wasting processing and slowing everything down, you may not be able to change everything you need to and/or you may cause side effects if you change something you shouldn't have.
The easiest way to make this substitution would be to look for “<domain>:<port>/” and replace it with “<domain>:<port>/wud/”, but if you have a relative path or some javascript concatenate the URL at runtime, some substitutions won't occur and will cause some problems.
Anyway, below are the parameters that I tried to use and that **didn't** work fully:
```
sub_filter 'href="$host$host_port/' 'href="$host$host_port/wud/';
sub_filter 'src="$host$host_port/' 'src="$host$host_port/wud/';
sub_filter_once off;
sub_filter_types *;
``` 

Because of all this, I finally concluded that it makes more sense for the application to be built with /wud/, as this avoids the problems mentioned above.
I took a look at what you said, researched a few more things and tried various ways to change the source code and generate the UI with /wud/. I even managed to make it work through /wud/ directly on the Node port, but through Nginx there were still several javascript problems.
Below is the script:
```shell
#!/bin/bash
WUD_VERSION=6.5.0

echo "==================== Downloading WUD $WUD_VERSION ===================="
curl -Lso wud-$WUD_VERSION.tar.gz https://github.com/fmartinou/whats-up-docker/archive/refs/tags/$WUD_VERSION.tar.gz
tar -xzf wud-$WUD_VERSION.tar.gz

cd ./whats-up-docker-6.5.0/ui/ || exit 1

echo "==================== Configuring vue.config.js to use /wud/ as base_url ===================="
sed -i "s/^module.exports = {/module.exports = {\n  publicPath: '\/wud\/',/" vue.config.js

echo "==================== Building UI ===================="
docker run --rm -u1000 -v "$PWD":/app -w /app -ti node:18 bash -c "\
  cp -r /app/ /tmp/ && \
  cd /tmp/app/ && \
  npm install && \
  npm run build && \
  mkdir /app/dist/ && \
  cp -r ./dist/ /app/dist/wud/"

cd ../ || exit 1

echo "==================== Building Docker image ===================="
docker build -t whats-up-docker:$WUD_VERSION -t whats-up-docker:latest .

cd ../ || exit 1

echo "==================== Cleaning files ===================="
rm -rf whats-up-docker-$WUD_VERSION
rm -rf wud-$WUD_VERSION.tar.gz

echo "==================== Starting WUD ===================="
docker run --name whats-up-docker-test --rm -p 3000:3000 -d whats-up-docker:latest
```

**Comment by olylak** [comment]
Hello @fmartinou, 
Is it still the case and cannot be implemented? 

This statement was done 2 years ago, maybe something changed from that time.

Great product! But unfortunatelly, without proper relative path support under revers-proxy, like traefik, it cannot be used by all users.

Thank you
