### ISSUE TITLE
Unsupported registry unknown

### ISSUE THREAD

**Issue by mattdale77** [fmartinou/whats-up-docker#249]
I get the following error for three containers at startup (the container name differing)
WARN whats-up-docker/watcher.docker.local: Error when processing (Unsupported Registry unknown) (container=local_overseerr)

Prior to this is this error:
WARN whats-up-docker: local_overseerr - No Registry Provider found

What is causing this and how do I resolve it?

**Comment by mattdale77** [comment]
I have managed to resolve this myself but I'm not sure if it's a bug or not so I'll leave this open until it is acknowledged.

SOLUTION:
The image file in my docker-compose for this container was:

image: lscr.io/linuxserver/overseerr

Removing the lscr.io solved the issue for the three containers that had this. I'm also experiencing other errors with some containers that have ghcr.io as the top level.

From this I believe it to be a bug with 3 level container naming

**Comment by fmartinou** [comment]
Hi,

If you're using images from other registries than Docker Hub, you need to give enable them on `wud`.

For example:
- [LSCR.io support](https://fmartinou.github.io/whats-up-docker/#/configuration/registries/lscr/)
- [GHCR.io support](https://fmartinou.github.io/whats-up-docker/#/configuration/registries/ghcr/)

As mentioned in the doc, without any configuration, only the following registries are by default enabled:
- ECR (public images only)
- GHCR (public images only)
- HOTIO
- HUB
- QUAY

**Comment by marcusique** [comment]
I'm having the same issue and I can't seem to find a solution.

My WUD config has WUD_REGISTRY_GHCR_TOKEN=xxx, but for all compose files with ghcr.io/xxx/yyy:latest it fails with Unsupported Registry unknown. Any ideas why @fmartinou?

```
14:17:43.587  WARN whats-up-docker: local_changedetection - No Registry Provider found
14:21:19.708  WARN whats-up-docker/watcher.docker.local: Error when processing (Unsupported Registry unknown) (container=local_changedetection)
```

GHCR is also missing from the list of available registries under /configuration/registries

![Screenshot 2023-05-02 at 14 24 54](https://user-images.githubusercontent.com/23212368/235665414-3974249e-1ba5-4b69-bcd9-d06cf621fbba.png)

**Comment by enticedwanderer** [comment]
I had the same problem as @marcusique after upgrading and it turned out that the ENV variables for the usernames (that are no longer necessary) were preventing the registry from initializing properly for GHCR and LSCR. Once I removed them it was picked up correctly with just the tokens. It might be a good idea to ignore unknown variables in the registry scope as this change was basically backwards incompatible and breaking.

**Comment by fmartinou** [comment]
Hi @marcusique ,

If you take a look at the startup log, you should see errors related to the initialization of the GHCR registry.
As @enticedwanderer said, it's probably because of a configuration error (missing or extra env var).

In the latest versions, the only needed env var is `WUD_REGISTRY_GHCR_TOKEN`.
