### ISSUE TITLE
[SOLVED] Radarr, Sonarr, Jackett and overseerr - No Registry Provider found

### ISSUE THREAD

**Issue by raynoxfr** [fmartinou/whats-up-docker#261]
Hello,

I have installed what's up docker and read the documentation about register : 
https://fmartinou.github.io/whats-up-docker/#/configuration/registries/hub/

I have configured  like that my docker compose :

```
version: '3'

services:
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: whatsupdocker
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WUD_REGISTRY_HUB_LOGIN= REPLACED
      - WUD_REGISTRY_HUB_PASSWORD= REPLACED
      - WUD_AUTH_BASIC_ADMIN_USER= REPLACED
      - WUD_AUTH_BASIC_ADMIN_HASH=REPLACED
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_proxy
    labels:      
      - "traefik.enable=true"
      - "traefik.http.routers.whatsupdocker.rule=Host(`docker-update.domain.net`)"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.whatsupdocker.entrypoints=websecure"
      - "traefik.http.routers.whatsupdocker.tls.certresolver=myresolver"
      - "traefik.http.services.whatsupdocker.loadbalancer.server.port=3000"
      

networks: 
  traefik_proxy:
    external: true
```

When I launch the docker, I get this erreur :
```

14:34:49.160  WARN whats-up-docker/watcher.docker.local: Error when processing (Unsupported Registry unknown) (container=local_radarr)
14:34:49.161  WARN whats-up-docker/watcher.docker.local: Error when processing (Unsupported Registry unknown) (container=local_sonarr)
14:34:49.162  WARN whats-up-docker/watcher.docker.local: Error when processing (Unsupported Registry unknown) (container=local_jackett)
14:34:49.163  WARN whats-up-docker/watcher.docker.local: Error when processing (Unsupported Registry unknown) (container=local_overseerr)
```

I don't know why, because I have HUB docker.

For example, the image used for sonarr :
    image: lscr.io/linuxserver/sonarr:latest

Thank for you help

**Comment by raynoxfr** [comment]
I tried for 2 days... it's necessary to post to find the solution :
Add : "WUD_REGISTRY_LSCR_TOKEN" with the token from GitHub.

Thank you ;)

**Comment by fmartinou** [comment]
Hi,

You're pulling images from LinuxServer.io (**LSCR.IO**/linuxserver/sonarr:latest) not from the HUB.

So you have to configure the related [LSCR registry](https://fmartinou.github.io/whats-up-docker/#/configuration/registries/lscr/) integration.

> I tried for 2 days... it's necessary to post to find the solution :

That's too bad because the documentation is, from my point of view, pretty clear about that:

https://fmartinou.github.io/whats-up-docker/#/configuration/registries/
![image](https://user-images.githubusercontent.com/16061231/229358031-2e31813c-77b6-4210-bbe9-377372f4940c.png)

![image](https://user-images.githubusercontent.com/16061231/229358334-84cb3265-5bab-4510-be67-8ca06a51b385.png)

Anyway, I'm glad you sorted it out 😃.
