### ISSUE TITLE
Is it possible to have multiple registries without providing credentials?

### ISSUE THREAD

**Issue by ajgon** [fmartinou/whats-up-docker#31]
So, here is my use case - I'm pulling most of my images from Docker Hub. However I also have few fetched from GCR (`cadvisor` is one of them for example). Is it possible, to configure multiple registrars without providing a token? So I can monitor GCR in a similar was as I monitor Hub ("anonymously")?

I also tried to create and configure GCR token, which worked fine. However then I'm missing my hub registry. I can configure it with auth, but I want to use it without authentication as I used it before - alongside with GCR. Is it possible? I tried setting `WUD_REGISTRY_HUB` to empty string, false or `{}` but with no luck.

**Comment by fmartinou** [comment]
Hi,

I understand your issue :/

My explanations:
- when no registries are defined, wud creates a default one configured to watch the Docker Hub anonymously
- when you define another registry (e.g. GCR), wud doesn't create this default configuration anymore
- when you try to configure the Docker Hub Registry yourself... you cannot because it's driven by defining authentication credentials
...

It wasn't intended; I'll find a way to fix it.

One additional question; do you also need to configure GCR without authentication?
I thought it wasn't possible to pull images from GCR anonymously.

**Comment by ajgon** [comment]
Anonymous GCR falls to "nice to have" category - I'm expecting, that Google won't give this sweet tracking data so easily :) I'm pulling majority of my images from Docker Hub anyway, so this is the thing which matters for me the most.

Thank you!

**Comment by fmartinou** [comment]
Could you give a try to the version `fmartinou/whats-up-docker:develop` and set `WUD_REGISTRY_HUB_AUTH=""`, please?
It should allow you to mix your GCR config and the anonymous Hub config.

Thanks

**Comment by ajgon** [comment]
Works like a charm :metal:

**Comment by fmartinou** [comment]
Fixed in `3.3.1`
