### ISSUE TITLE
Add support for Github Container Registry

### ISSUE THREAD

**Issue by sodoto** [fmartinou/whats-up-docker#49]
Hi! Pretty new to everything related to docker. So I just installed Wud and I was wondering if it's normal that the registry of my images from Linuxserver are not recognised? Ex.: `ghcr.io/linuxserver/radarr`

I tried to remove the `ghcr.io` and only use `linuxserver/radarr` and it's working fine. Is it supposed to be normal?

Thank you!

**Comment by fmartinou** [comment]
Hi,

I didn't know that Linux server images were also available on [Github Registry](https://github.com/features/packages).

The fact is that when you run:
- `docker pull ghcr.io/linuxserver/radarr`, you pull an image hosted on [Github packages](https://github.com/features/packages)
- `docker pull linuxserver/radarr`, you pull an image hosted on [Docker hub](https://hub.docker.com)

Currently WUD supports [some Registries](https://fmartinou.github.io/whats-up-docker/#/configuration/registries/) including Docker Hub but not Github packages.
(that's why it's working when you remove `ghcr.io/`

I add the support for Github packages to my todo list.
(if it implements the [official Docker Registry V2 API](https://docs.docker.com/registry/spec/api/), it shouldn't be too difficult).

**Comment by sodoto** [comment]
Hi, thank you for the quick reply and for your explanation, I'll use the images hosted on docker for now on.

Merci pour ton travail!

**Comment by fmartinou** [comment]
Github container Registry support has been added to `5.2.0`
