### ISSUE TITLE
Entity Id in Home Assistant

### ISSUE THREAD

**Issue by ioull** [fmartinou/whats-up-docker#86]
I just integrate wud in my homelabs and it is very nice ! Thanks for your work !
I use it in home assistant in order to be informed of the updates. I use the customize (https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui) option in order to rename it and change the icon like that :
![image](https://user-images.githubusercontent.com/6410144/144012584-2f30fcc6-7410-42b0-9d01-2fc814b5a7a0.png)
But after a restart or an update of the concerning docker, I suppose the entity id change in home assistant so I loose my customisation like you can see for adguardhome in my previous screenshot.

Any idea to fix that ?

**Comment by fmartinou** [comment]
Hi,

I get your point (actually, I have the same issue; I set custom labels on the entities and they're gone anytime a new update has been found).

I don't think that entity_id is the root problem because it remains the same before/after the update (e.g. `wud_container_local_adguardhome`).

Maybe the problem is caused by the fact that WUD sends an mqtt message indicating that the container has been removed (the previous version)then, few seconds after, it sends a second mqtt message indicating that a new container has been added (the new version with the same id, btw).
I guess that this 'remove then add' operation leads HomeAssistant to destroy & create the sensor and loosing the customization... 🤔 

I'll try to find a solution.

**Comment by ioull** [comment]
An idea (ugly ?) is to add labels for name and icon for example : 
  - wud.ha.icon=mdi:home
  - wud.ha.friendlyname = MonJoliNom
so you can push to config those values in fields name and icon ? 
Not really a fix but a workaround ...

**Comment by fmartinou** [comment]
I like your idea!

It's an interesting improvement; I log it to my todo list 👍 .
(and it doesn't prevent me from looking for a real solution for your issue in the meantime ;)

**Comment by SNoof85** [comment]
Hi !
Any update on it ?
My lovelace card doesn't look so good 👎 

![image](https://user-images.githubusercontent.com/25659602/152437447-e6779709-24dd-4586-88a1-d28cf9cf9df5.png)

**Comment by fmartinou** [comment]
Hi,

This shouldn't be hard to implement, I agree ; I'm just running out of time...
I'll try to implement it this week-end (no promise)

**Comment by fmartinou** [comment]
Hi,

It's done 😃 

Rather than implementing something specific for Home-Assistant, I've added a feature allowing to globally customize the container name+icon (it's used in WUD UI as well as for home-assistant entities).

Below how it looks on my HA.
![image](https://user-images.githubusercontent.com/16061231/152647396-3ea79c79-b869-430a-b678-7090ae5c21f8.png)

- [The documentation](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=labels)
- [An example](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=customize-the-name-and-the-icon-to-display)

The feature is available in version `5.15.0`

**Comment by SNoof85** [comment]
That's is awesome !
I forked the project and was about to get a try but you were faster ! I'm not very confident when it comes to any language containing "java" 🤣

**Comment by SNoof85** [comment]
Gave it a try, that's working fine -BUT- all entities are now created like `binary_sensor.<display.name>` and before this, it was `binary_sensor.wud.<container_name>`
With the prefix `binary_sensor.wud*` it was simple to get all entities coming from wud with an auto-entities card (wich i'm using).
Now I have to grab them all by hand and if a new container pops up in my stack I will have to add it manually to the card.
This is not very important but could be another improvement on HA side.
